nginxinc/nginx-hugo-theme

- .gitignore
- CONTRIBUTING.md
Update the gitignore and CONTRIBUTING files.
> chore: update gitignore and contributing files

- layouts/partials/scripts.html
- layouts/partials/styles.html
Fixes #4 
This PR updates the scripts and styles partials to use the most recent version of the Coveo UI: https://docs.coveo.com/en/328/javascript-search-framework/javascript-search-framework-v2-2022-releases#december-2022-release-v2101040
Tested in [docs-dev deploy](https://app.netlify.com/sites/docs-dev-nginx/deploys/64762ea31181541cdb8b97f9)
> Fixes #4: update coveo jsui version

- layouts/partials/scripts.html
Update Coveo prod, dev, and staging environment keys
DOC-83
> fix: update coveo prod, dev, and staging keys

- assets/css/f5-hugo.css
- assets/js/code-copy.js
- layouts/partials/scripts.html
Adds an interactive copy button to code blocks to copy the content to the clipboard.
> feat: add copy button to code blocks

- assets/css/f5-hugo.css
remove the button bottom border for aesthetic reasons
> fix: tiny CSS fix

- layouts/ossc/single.html
- layouts/partials/footer.html
Add FOSSA link to the footer. Add custom layout for the Fossa page.
> feat: add fossa link

- layouts/partials/footer.html
> fix: footer fix

- README.md
- Added a step to create an index.md file when implementing the include shortcode
> fix: added create index.md to include shortcode steps

- assets/css/docs-nginx-com/style.css
Fix the dark background on coveo quick preview 
> fix: fix dark background in quick preview

- assets/css/coveo.css
Update the coveo quickview BG color to an approved shade of green
> chore: change coveo quickview bg

- assets/css/f5-hugo.css
- Tab improvements to increase visibility
- Copy button changes for consistency with tab style
> feat: tab improvements

- layouts/partials/toc.html
Fix the TOC title to Title Case
> fix: fix TOC title case

- layouts/shortcodes/download.html
Adds a new shortcode that lets you provide a download link to a file
Describe the use case and detail of the change. If this PR addresses an issue on GitHub, make sure to include a link to that issue using one of the [supported keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) here in this description (not in the title of the PR).
> Create download shortcode

- assets/css/f5-hugo.css
- assets/js/sidebar.js
- Fixed issue with sidebar not animating when collapsing
- Fixed issue on mobile where max-width would be 50%, leading to some blank space
> Sidebar layout fix

- assets/css/f5-hugo.css
Updated css for new N1 console landing page. 
Ticket here: https://github.com/nginxinc/docs-platform/issues/200
> feat: updated hugo theme for new n1 landing page

- assets/css/f5-hugo.css
- Renamed classes for cards in NGINX One product landing page.
> chore: renamed class names for cards on n1 landing page

- layouts/partials/footer.html
- Add `F5 NGINX One` to footer of site
> feat: added f5 nginx one to footer product list

- assets/css/f5-hugo.css
- layouts/partials/header.html
Fixed issue on safari where icon was aligned incorrectly on the sidebar
> Sidebar safari header

- assets/js/coveo.js
Fixed coveo analytics endpoint according to these suggestions: https://docs.coveo.com/en/mcc80216/manage-an-organization/organization-endpoints#analytics-endpoint
Before:
After:
> fix: fixed analytics endpoint for coveo

- layouts/partials/qualtrics-feedback.html
Add hr and padding around survey
> Add hr and padding around survey

- layouts/partials/footer.html
Update the copyright year to 2025
Describe the use case and detail of the change. If this PR addresses an issue on GitHub, make sure to include a link to that issue using one of the [supported keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) here in this description (not in the title of the PR).
> Bump copyright year to 2025

- SUPPORT.md
Closes https://github.com/nginxinc/docs/pull/1569
> Remove mention of community Slack

- assets/css/f5-hugo.css
Closes https://github.com/nginxinc/docs-platform/issues/246
> Remove sidebar background

- layouts/partials/qualtrics-feedback.html
Reverted changes from https://github.com/nginxinc/nginx-hugo-theme/pull/105
> chore: remove SourcePage from qualtrics src

- layouts/_default/baseof.html
Add display none to mf searchbox
> Add display none to mf searchbox

- layouts/_default/docs.html
Fix double toc from bad rebase
> Fix double toc

- assets/js/product-selector.js
Refactor jquery from product selector
> Refactor jquery from product selector

- layouts/_default/baseof.html
> Add v2 to coveosearchbox mf

- assets/css/v2/style.css
- layouts/_default/baseof.html
- layouts/partials/footer-v2.html
Closes out: https://github.com/orgs/nginxinc/projects/33/views/4?pane=issue&itemId=94389468&issue=nginxinc%7Cdocs-platform%7C319
> feat: added footer

- assets/css/v2/style.css
- assets/js/product-selector.js
- layouts/partials/sidebar-v2.html
- Changing font weight on sidebar to be thinner.
- Refactored sidebar lines to be centered.
- Converted from `rem` to `px`.
- Changed the JS for the site dropdown to remove border at the bottom when dropdown is active.
> Sidebar improvements

- assets/css/v2/style.css
- layouts/_default/baseof.html
- layouts/partials/footer-v2.html
- layouts/partials/footer.html
Closes: https://github.com/nginxinc/docs-platform/issues/340
> feat: added trustarc to footer v2

- assets/css/v2/style.css
- layouts/_default/_markup/render-codeblock.html
- Closes: https://github.com/nginxinc/docs-platform/issues/327
> Added codeblocks to mainframe

- .gitignore
- exampleSite/archetypes/default.md
- exampleSite/content/nginx/_index.md
- exampleSite/content/nginx/installing-nginx-open-source.md
- exampleSite/go.mod
- exampleSite/hugo.toml
- exampleSite/layouts/index.html
Add basic exampleSite for testing theme
> Add basic exampleSite for testing theme

- assets/css/f5-hugo.css
Closes: https://github.com/nginxinc/docs-platform/issues/362
> fix: broken N4A cost calculator formatting

- layouts/_default/_markup/render-codeblock.html
- layouts/partials/toc.html
Fixed issue related to thread internal thread.
> fix: toc not rendering correctly

- .github/workflows/hugo-build-test.yml
Run action automatically on PRs against main
> Tooling: Use correct go version syntax

- biome.json
- layouts/partials/qualtrics-feedback.html
- Added qualtrics support for `staging` env.
> Add Qualtrics to Staging

- assets/css/v2/style.css
Fix left margin padding on product selector
> Sidebar: Add padding to top of sidebar when sticky

- assets/css/v2/style.css
Closes: https://github.com/nginxinc/docs-platform/issues/376
> Add Mainframe Tabs

- layouts/_default/baseof.html
ThemeSwitcher: Use gameCode fn and var names
> ThemeSwitcher: Use gameCode fn and var names

- assets/css/v2/style.css
- assets/js/coveo.js
- layouts/_default/baseof.html
- layouts/partials/scripts.html
- layouts/partials/styles.html
- layouts/search/single.html
Closes: https://github.com/nginxinc/docs-platform/issues/252 and https://github.com/nginxinc/docs-platform/issues/181
Old theme:
New theme:
> Updated coveo to use Atomic + support coveo on Mainframe

- assets/css/v2/style.css
Closes https://github.com/nginxinc/docs-platform/issues/381
> Changed mainframe breakpoints

- assets/css/v2/style.css
Closes https://github.com/nginxinc/docs-platform/issues/386
Before:
After:
> Adjusted coveo styling to match mainframe more

- assets/css/v2/style.css
Closes https://github.com/nginxinc/docs-platform/issues/379
Before:
After:
> Constraint images to the parent div

- assets/css/v2/style.css
Closes https://github.com/nginxinc/docs-platform/issues/400
Before:
After:
> Remove border from codeblocks in callouts

- assets/css/v2/style.css
Closes https://github.com/nginxinc/docs-platform/issues/392
Before (denoted as a small dot in the top center): 
After:
> Hr tags not rendering

- assets/css/v2/style.css
Closes https://github.com/nginxinc/docs-platform/issues/409
Before:
After:
> Cleaned up codeblock code + fixed up issue with bottom border

- layouts/partials/sidebar-list-pages.html
Closes https://github.com/nginxinc/docs-platform/issues/414
> Render TOC only for current page

- assets/css/v2/style.css
Closes https://github.com/nginxinc/docs-platform/issues/411
> Update sidebar icon + animation

- layouts/partials/breadcrumb.html
Closes: nginxinc/docs-platform#408
Describe the use case and detail of the change. If this PR addresses an issue on GitHub, make sure to include a link to that issue using one of the [supported keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) here in this description (not in the title of the PR).
> Styles: Remove extraneous whitespace in breadcrumbs

- assets/css/v2/style.css
Closes https://github.com/nginxinc/docs-platform/issues/455
> Codeblock rendering with extra options

- layouts/_default/docs.html
- layouts/_default/list.html
CloudCannon: Add editable area attributes. For you with https://cloudcannon.com/documentation/guides/unified-configuration-migration-guide/other-configuration/
> CloudCannon: Add editable area attributes

- assets/css/v2/style.css
Closes https://github.com/nginxinc/docs-platform/issues/444
> Adjusted size of images

- assets/css/v2/style.css
- layouts/partials/sidebar-v2.html
Closes https://github.com/nginxinc/docs-platform/issues/447
Before:
After:
> fix: Sidebar TOC render on root links

- assets/css/v2/style.css
Closes https://github.com/nginxinc/docs-platform/issues/478
Before:
After:
> Images aspect ratio not working

- assets/css/f5-hugo.css
> Safari img width bug

- assets/css/f5-hugo.css
Closes https://github.com/nginxinc/docs-platform/issues/481
Before:
After:
> Set fixed max width on card images

- assets/css/v2/style.css
- layouts/_default/list.html
Closes https://github.com/nginxinc/docs-platform/issues/486
> Coveo not showing properly on product landing + some devices

- layouts/shortcodes/bootstrap-table.html
Closes https://github.com/nginxinc/docs-platform/issues/445
Before:
After:
> Double header on bootstrap table

- assets/css/v2/style.css
Closes https://github.com/nginxinc/docs-platform/issues/484
> Updated OL and UL tag spacing

- assets/css/v2/style.css
Closes https://github.com/nginxinc/docs-platform/issues/469 and https://github.com/nginxinc/docs-platform/issues/467
> Conform colors into better var names

- Makefile
Fix issue with Biome downloading `latest` in Makefile.
Tied to version 1.9.4. 
> Fixed issue where biome downloads latest

- layouts/partials/coveo-atomic.html
Closes https://github.com/nginxinc/docs-platform/issues/377
New Filter:
Russian clicked:
> Added language filter to coveo

- assets/css/v2/style.css
Closes https://github.com/nginxinc/docs-platform/issues/534
Before:
After:
> Fixed redocly responsive on new grid

- layouts/partials/banner.html
Small tweak to the banner partial
> Refactored class name based off type for banner

- assets/css/v2/style.css
- layouts/partials/qualtrics-feedback.html
Change footer background to white
Reduced "Last modified" section font size
Remove horizontal rule from survey section
Describe the use case and detail of the change. If this PR addresses an issue on GitHub, make sure to include a link to that issue using one of the [supported keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) here in this description (not in the title of the PR).
> Footer: Make background white

- assets/css/v2/style.css
- layouts/partials/header.html
Closes https://github.com/nginxinc/docs-platform/issues/563
Before:
After:
> Fixed "F5 Sites" button and content alignment

- .github/workflows/release-build.yml
Closes https://github.com/nginxinc/docs-platform/issues/564
> Added description object to new release workflow

- layouts/partials/coveo-atomic.html
Closes https://github.com/nginxinc/docs-platform/issues/532
Preview
> Add new product category facet to coveo

- assets/js/coveo.js
Coveo: Fix bad token initial load
When there was no valid token in local storage, we would set the value in local storage but _not_ set the values being passed to coveo. So the first load of the component would always fail, and then be fine after a refresh.
Also refactored some of the repeated component initialization code.
> Coveo: Fix bad token initial load

- .github/workflows/release-build.yml
Closes https://github.com/nginxinc/docs-platform/issues/616
> Update release-build to only work if there is a full release

- assets/css/v2/style.css
- assets/js/product-selector.js
- assets/js/site-dropdown.js
- exampleSite/data/product-selector.yaml
- layouts/partials/header.html
- layouts/partials/sidebar-v2.html
TODO: 
Overview:
- Restyle coveo search box
- Restyle F5 Sites button
- Move search box to left side
- Move sidebar toggle to main header
- Move product selector to sidebar
> Header: Mainframe header redesign

- assets/css/v2/style.css
> ProductSelector: Show pointer on summary section

- assets/css/v2/style.css
- layouts/search/single.html
> Fix coveo results would overflow on mobile

- layouts/partials/sidebar-v2.html
ProductSelector: Normalize URL comparison for product
> ProductSelector: Normalize URL comparison for product

- assets/css/v2/style.css
- Fix issues with "Sort & Filter" button on mobile screens.
Before:
https://github.com/user-attachments/assets/44f28211-75f7-4d1e-ad9b-2a7d5efca249
After:
https://github.com/user-attachments/assets/07ed83f3-e2e6-4d27-a5d1-14c528b63b80
> Fix sort and filter rendering on mobile for coveo

- assets/css/v2/style.css
> Callouts: Prevent codeblocks overflowing callouts

- assets/css/v2/style.css
> Fix alignment on TOC
