- layouts/partials/sidebar.html
- Add a 4th level to the navigation bar (fixes sections that stopped working after being pushed 1 level deeper)
- When loading one product's landing page, the Level 1 sections for the product expand automatically
> feat: Fix navigation bar issues

- layouts/partials/sidebar.html
Changes the logic that generates the collapsible sections ID and HREF in the navigation bar to include the section and subsection in the string. This fixes several sections with the same name expanding/collapsing together.
> fix: sections with same name expand together

- layouts/partials/sidebar.html
Fixes L2 sections with same name expanding at the same time
> fix: fix l2 sections with same name

- CHANGELOG.md
- layouts/partials/sidebar.html
This change in the sidebar allows single pages to show before sections of the same depth level, based on the frontmatter weights.
Before:
After:
> feat: weight order affects sections/pages

- layouts/shortcodes/icon-info.html
- Created an icon-info shortcode to be used in RNs and KI docs.
- Resolves https://nginxsoftware.atlassian.net/browse/DOC-199
Looks like this:
> fix: added icon-info shortcode

- assets/js/code-copy.js
Change to make the copy button work only with highlighted code blocks
> fix: copy button on non highlight blocks

- assets/css/f5-hugo.css
- layouts/partials/header.html
Remove border in the top right Explore button,  introduced accidentally while updating tabs CSS.
> fix: fix explore button border

- assets/js/code-copy.js
bugfix for docs-386
Remove return carriage from copied text as it causes code pasted into a terminal to execute automatically.
> fix: remove return carriage from copied text

- assets/js/sidebar.js
- layouts/partials/list-main.html
Imports the list-main.html changes from the docs repo to the theme
- This change makes items in the list pages appear in the same order as they appear in the side navigation
Improves the navigation bar:
- When browsing a section list-page the navigation will highlight the section and (new) expand it to show the same subsections as the list page is showing:
before:
after:
Closes DOC-146
> fix: order for list pages + navbar improv

- layouts/partials/list-main.html
List pages will respect weights to order the items (sections and pages)
Uses part of the code from the docs repo for the same solution. 
> fix: fix landing page rendering with weight order

- assets/js/coveo.js
- layouts/partials/scripts.html
Previously the values of each Coveo API key were hardcoded into the hugo theme code in `layouts/partial/scripts.html` which would pass the appropriate key value to the `js.Build` command. This would result in the api key being embedded in the minified javascript code, and observable via the inspection tools in a web browser.
This change removes those hardcoded values and replaces them with an API call to a Netlify function which will return the value of the `COVEO_SEARCH_TOKEN` variable from the Netlify site's environment variables.
> Replace hardcoded Coveo api keys with  a call to Netlify function

- assets/css/docs-nginx-com/style.css
Remove scroll-behavior smooth to fix anchor links in redocly.
There's at least one open issue with similar behavior https://github.com/Redocly/redoc/issues/1333.
> remove scroll-behavior smooth

- assets/css/f5-hugo.css
- assets/js/sidebar.js
- layouts/_default/docs.html
Adds a sidebar toggle feature that uses localStorage to keep track of user preferences to display or hide the left navigation bar. This is useful for viewing the API docs and having access to navigation.
Closes #42 
] I have updated any relevant documentation ([`README.md`](https://github.com/nginxinc/nginx-hugo-theme/blob/main/README.md) and [`CHANGELOG.md`](https://github.com/nginxinc/nginx-hugo-theme/blob/main/CHANGELOG.md))
> Add toggle-able sidebar button

- assets/css/f5-hugo.css
Fixes an issue with the boxes in the Other NGINX products section when we have more than 2 products
> fix: update CSS for other products section

- assets/css/docs-nginx-com/style.css
- layouts/shortcodes/img.html
fixes an issue rendering SVGs with border
> fix: fix SVG css

- assets/css/docs-nginx-com/style.css
- assets/css/f5-hugo.css
Adds the CSS border to screenshots not using the img shortcode which are using the markdown notation `![alt](src)`
> chore: add border to md screenshots

- layouts/shortcodes/details-disclosure.html
Instances of details/summary blocks on the docs site include icons in the summaries (e.g., fa-file). The details shortcode did not have any option for adding icons. This PR introduces two new params:
- a boolean on whether to include an icon prefix or not
- the icon string to be used in the &lt;i&gt; class
> Feat: add icon prefix option to disclosure shortcode

- layouts/partials/catalog-toc.html
- layouts/partials/toc.html
Fix for https://github.com/nginxinc/nginx-hugo-theme/issues/61
Adds a custom table of contents. You can now include a `catalogType` when `toc` is true. The catalogType will be used to render the content of `.Site.Data.${catalogType}` as a list.
For example
``` md
toc: true
catalogType: nms.catalogs.events
```
> Add custom table of contents partial for use with catalog

- assets/js/coveo.js
This update the `search_token` endpoint to be `/api/v1/auth/search_token`.
The reasons for this are;
- Moving away from any netlify references
- Forcing a new endpoint will break the token stale cache issue
- Moving to a "versioned" endpoint will make for cleaner update going forward
> change search_token endpoint to non netlify path

- layouts/404.html
- layouts/partials/favicon.html
- layouts/partials/footer.html
- layouts/partials/header.html
- layouts/partials/meta.html
- layouts/partials/sidebar.html
- layouts/search/single.html
- layouts/success/single.html
Replaces .Site.BaseURL with absURL as per https://gohugo.io/methods/site/baseurl/
for example:
`<p><a href="https://www.f5.com/"><img class="f5-logo-footer" src="{{.Site.BaseURL}}/images/icons/Logo_F5.svg" alt="F5 logo"></a>`
becomes 
`<p><a href="https://www.f5.com/"><img class="f5-logo-footer" src="{{ "/images/icons/Logo_F5.svg" | absURL }}" alt="F5 logo"></a>`
> fix: replace .Site.BaseURL with absURL in templates

- layouts/partials/footer.html
hardcode the ossc link in the footer. This link is in the theme and is not product url dependant, which causes it to break on repos other than `docs`
> docs: hardcode ossc link in footer

- assets/css/f5-hugo.css
- layouts/shortcodes/before-you-begin.html
- layouts/shortcodes/call-out.html
Adds the call-out and before-you-being used in the docs repo to the theme.
Adds the CSS that was used in custom tables for NGINX One to the default styles for all tables.
before:
after:
Follow ups after merge and release:
- Remove the shortcodes from the layouts folder in the docs repo
- Remove the custom styles in the NGINX one docs/branch
- Bump the theme/rebuild the docs in the `docs` repo
> docs: add shortcodes and CSS

- assets/css/f5-hugo.css
- layouts/partials/footer.html
Updates the Social column in the footer to be only icons.
Replaces the Twitter icon with the _X_ icon
Issue [#764](https://github.com/nginxinc/docs/issues/764)
> docs: update social footer twitter > X

- layouts/_default/docs.html
- layouts/feedback/single.html
- layouts/ossc/single.html
- layouts/partials/list-main.html
- layouts/partials/page-summary.html
- layouts/partials/taxonomy-list.html
This pull request removes meta descriptions from displaying in user-facing HTML.
It's a long-standing bug with the theme.
> Remove meta descriptions from displaying in user-facing HTML

- layouts/_default/baseof.html
- layouts/partials/meta.html
- theme.toml
Calls to `.Site.IsServer` were preventing upgrading to a newer version of Hugo.
As such, the minimum supported version has been bumped.
Related: https://github.com/nginxinc/docs-platform/issues/205
> chore: update deprecated helper functions

- assets/css/v2/style.css
- assets/js/theme-switcher.js
- layouts/partials/scripts.html
- layouts/partials/styles.html
Add _very_ basic theme switcher. 
It can be toggled in the developer console using `useNewTheme(true)` to enable the new theme or `useNewTheme(false)` to disable it.
The last value set is stored in local storage so you can browse around the site with your theme of choice.
There's a slightly flicker changing pages on the new theme, since the old theme is enabled by default.
> Add console based theme switcher

- assets/css/f5-hugo.css
- assets/js/product-dropdown.js
- layouts/partials/header.html
- layouts/partials/scripts.html
- Removed "Explore all products" button on navbar.
- Added link dropdown in its place to links to `DevCentral`, `MyF5`, and `nginx.org` 
Closes https://github.com/nginxinc/docs-platform/issues/199 
Supplements https://github.com/nginxinc/docs/pull/1147
> feat: update docs landing page

- README.md
- layouts/shortcodes/ghcode.html
Adds shortcode for rendering github content at build time.
```
{{< ghcode "https://raw.githubusercontent.com/nginxinc/kubernetes-ingress/refs/heads/main/examples/custom-resources/access-control/access-control-policy-allow.yaml" "hl_lines=4" >}}
```
If the url provided does not exist, it will throw an error referencing the url and source of shortcode usage.
```
ERROR Unable to load github content from https://raw.githubusercontent.com/nginrnetes-is/heads/main/examples/custom-resources/access-control/access-control-policy-allow.yaml from "\x1b[1;36m\"/Users/j.hickey/Documents/github/docs/content/nginx-one/about.md:29:1\"\x1b[0m"
```
> Add ghcode shortcode for rendering github content

- assets/css/inline-overrides.css
- layouts/_default/baseof.html
- layouts/_default/docs.html
- layouts/partials/api.html
- layouts/partials/header.html
- layouts/partials/styles.html
- layouts/shortcodes/table.html
This PR is necessary so that inline styles for the main Hugo theme don't interfere with Mainframe styles.
Comment from `assets/css/inline-overrides.css`:
```css
/*
* These styles were previously defined inline in the theme as hacks. They
* live here so we know where they came from.
*
* Where necessary, new classes were defined in their place so they don't 
* interfere with the new theme CSS. (e.g. .override-sidebar-collapse)
**/
```
> Move inline styles to a separate CSS files

- assets/css/f5-hugo.css
- layouts/_default/docs.html
Add last-modified section to bottom of docs pages.
> Add last-modified section to bottom of docs pages

- layouts/shortcodes/dimensions.html
- layouts/shortcodes/metrics.html
- Replaced getJSON with transform.Unmarshal in `dimensions.html` and `metrics.html`
> fix: replaced getJSON with transform.Unmarshal

- assets/js/code-copy.js
Change selector used to the .highlight class
Add regex to remove line numbers
Update regex to remove carriage returns start and end of block
> Fix lineos=true breaking copy to clipboard

- assets/js/theme-switcher.js
- layouts/_default/docs.html
Add sidebar swapper.
**Expected behaviour:**
- On visiting the page without having used `useNewTheme`, the current side bar should be visible
- After running `useNewTheme(true)` in your browser console, the sidebar should be replaced with the text "Sidebar placeholder" and the new theme should be visible
- Running `useNewTheme(false)` should revert back to the current styling
- Refreshing the page should _keep the same state as before the refresh_, be it theme true or theme false
> Add sidebar swapper

- assets/css/f5-hugo.css
- layouts/_default/baseof.html
- layouts/_default/docs.html
- layouts/partials/meta.html
- layouts/partials/qualtrics-feedback.html
- Add qualtrics survey to bottom of every docs page (excluding landing pages)
- Ticket https://github.com/nginxinc/docs-platform/issues/260
> Qualtrics survey

- layouts/partials/qualtrics-feedback.html
- Added to src attribute a new parameter in order to retrieve the URL for qualtrics to read and present when looking at responses from customers.
- Requirements from Irving:
- Resolves: https://github.com/nginxinc/docs-platform/issues/294
> Fetching URL for qualtrics surveys

- assets/css/v2/style.css
- assets/js/theme-switcher.js
- layouts/_default/docs.html
Hide toc with theme switcher
Add x overflow for code blocks (code blocks will)
scroll horizontally instead of overflowing outside it's block
> mf - Use rem values from mockup

- assets/js/coveo.js
Add coveo jwt caching.
This change will store the coveo org id and token as a JWT in localstorage.
When the page is bootstrapping, it will check local storage for the token _and_ check if the token is valid.
It will use the token from cache if it's still valid, or make a request for a new one if it has expired.
The goal of this is to stop the persistent reloading of the search input box on page change, and this seems to achieve that 👌 .
Note: Security wise, this JWT is already visible in plain text looking in the network tab. Given coveos strict CORS and short token life, storing this in local storage isn't an issue.
> Add coveo jwt caching

- assets/js/sidebar-v2.js
- layouts/partials/scripts.html
- layouts/partials/sidebar-list-pages.html
- layouts/partials/sidebar-v2.html
Added JS code to the sidebar v2 to expand lines to current page
> added JS to automatically open sidebar v2 to current page

- assets/css/v2/style.css
- layouts/partials/sidebar-v2.html
Changed product name on the sidebar to be dynamic instead of hard-coded with "NGINX Plus"
> changed text on product name to be dynamic

- assets/css/v2/style.css
- layouts/partials/sidebar-v2.html
Closes: https://github.com/nginxinc/docs-platform/issues/343
> Added scroller to sidebar

- .github/CODEOWNERS
Update codeowners to use github teams
> Update codeowners to use github teams

- assets/css/v2/style.css
- layouts/_default/_markup/render-codeblock.html
Codeblocks: Use theme switcher for codeblocks.
Wraps the mf codeblock with the data-mf atribute, and renders the standard codeblock by default.
> Codeblocks: Use theme switcher for codeblocks

- assets/css/v2/style.css
- layouts/_default/_markup/render-codeblock.html
- layouts/_default/baseof.html
- Fix old codeblocks not hiding when using new theme.
- Fix left padding to align with content when no comment(s) is present.
Before:
After:
> Hde the v1 codeblocks on new theme + fix padding on v2 codeblocks

- assets/css/v2/style.css
- assets/js/code-copy.js
- assets/js/coveo.js
- assets/js/product-selector.js
- assets/js/sidebar-v2.js
- assets/js/sidebar.js
- assets/js/site-dropdown.js
- biome.json
Follow-up to https://github.com/nginxinc/nginx-hugo-theme/pull/143 to update all appropriate files.
> Linted all existing files using biome

- .pre-commit-config.yaml
- Makefile
- biome.json
- scripts/run-biome.sh
- Added Biome to pre-commit hook.,
> Add Biome to pre-commit

- CONTRIBUTING.md
- Makefile
pre-commit does not install commit-msg type hooks
by default. The make target will install all our
hook types automatically.
See https://pre-commit.com/#pre-commit-configyaml---top-level
Update CONTRIBUTING with new make target info.
> Tooling: Add setup-pre-commit make target

- .github/workflows/biome-lint.yml
- .github/workflows/commit-lint.yml
This will run against all branches pushed to
github and will block merges to main on failures.
> CI: Add commit and biome lint to CI

- .github/workflows/fossa.yml
- .github/workflows/mend.yml
Add fossa and mend github ci jobs
> Tooling: Add fossa and mend github ci jobs

- .github/workflows/hugo-build-test.yml
- .github/workflows/nginx-documentation-build.yml
CI: Add github action to build documentation repo
> CI: Add github action to build documentation repo

- layouts/_default/baseof.html
Adds new toggleTheme function, along with aliases for existing mf and useNewTheme functions. These functions can now be called as toggles, instead of explicitly passing a boolean i.e. `mf()` or `useNewTheme()` or `toggleTheme()` will toggle themes. Add aliases for mf and useNewTheme for backwards compatability.
**Additional toggle options**
When we fully release, we should have a "preview new theme" front and centre, until then, to encourage internal testing, 
Add konami code to toggle (i.e. up,up,down,down,left,right,left,right,B,A) , from any page on the site, will toggle the theme
> Theme: Toggle theme without passing boolean value

- assets/css/v2/style.css
- layouts/_default/baseof.html
Depends on: https://github.com/nginx/documentation/pull/236
Closes: https://github.com/nginxinc/docs-platform/issues/371
> Basic Redocly integreation in Mainframe

- assets/css/v2/style.css
Adjusted the margin of codeblocks without comments to be inline with text content.
Before:
After:
> Changed codeblock margin left to be non-zero if has comments

- assets/css/v2/style.css
- layouts/shortcodes/note.html
Closes https://github.com/nginxinc/docs-platform/issues/380
Before:
After:
> Removed note callout redundancy

- assets/css/f5-hugo.css
Allow qualtrics survey to be full height instead of capped at 350px by default from qualtrics.
Before:
After:
> Allow qualtric's article effectiveness survey to be full height

- assets/css/v2/style.css
Closes https://github.com/nginxinc/docs-platform/issues/382
Before:
After:
> Product selector z-index not being highest

- assets/css/v2/style.css
- layouts/shortcodes/tabs.html
Handle case in Tabs shortcode for large number of tabs. 
Before:
After:
> Handle large number of tabs via scroll

- .github/CODEOWNERS
This commit removes the writing half of the DocOps team from CODEOWNERS. It is primarily engineers that iterate on the theme: this change ensures that writers are not engaged with any in-flight work prematurely.
User testing will be explicitly requested when new elements or functionality have reached an appropriate state of development.
> feat: Remove DocOps Writers from CODEOWNERS

- assets/css/v2/style.css
- layouts/shortcodes/call-out.html
- Dependent on https://github.com/nginx/documentation/pull/277 before merging
- Closes https://github.com/nginxinc/docs-platform/issues/324
> Added side callout CSS

- assets/css/v2/style.css
- assets/js/code-copy-v2.js
- exampleSite/content/nginx/installing-nginx-open-source.md
- layouts/_default/_markup/render-codeblock.html
- layouts/_default/baseof.html
- layouts/partials/scripts.html
Codeblock: Add styling to base codeblock
> Codeblock: Add styling to base codeblock

- assets/css/v2/style.css
- layouts/_default/_markup/render-codeblock.html
Fixed issue with Codeblock rendering on old theme as seen on http://localhost:1313/nginx-app-protect-waf/v5/admin-guide/install/ locally
> Codeblock rendering incorrectly on old theme

- assets/css/v2/style.css
Fixes issue where there are vertical and horizontal lines showing when there is only a single item in the sidebar. 
Before:
After:
> Sidebar showing lines when there is a singular item

- assets/css/v2/style.css
Fixes how the breadcrumbs render on smaller resolutions so they are not squished. Below is on iPhone 11 Pro (375x812):
Before:
After:
> Breadcrumbs on smaller resolutions

- assets/css/v2/style.css
- layouts/_default/_markup/render-codeblock.html
- Update styling of copy button.
- Rework the code language.
> Update design on codeblock

- assets/css/v2/style.css
- layouts/shortcodes/tabs.html
- Fixed issue with Tabs not functioning due to `z-index: -1`.
- Ensured product selector is on top of everything 
> Tabs not working due to z-index

- assets/js/code-copy.js
- exampleSite/content/test-product/_index.md
- exampleSite/content/test-product/code-blocks.md
- exampleSite/layouts/index.html
Some code blocks that are being migrated from Unit have comments in the shell/console blocks in # form.
This update aims to improve the copy-code block javascript to detect and remove comments in shell code blocks.
It also updates the function to detect and remove # and $ at the beginning of console/bash commands
> feat: update copycode js

- assets/css/v2/style.css
- layouts/partials/sidebar-list-pages.html
Closes https://github.com/nginxinc/docs-platform/issues/365
> Added toc to sidebar

- assets/css/v2/style.css
- layouts/shortcodes/tabs.html
> Added small fade on tabs when scrollable

- assets/css/v2/style.css
https://github.com/user-attachments/assets/e913d069-91f2-4bd2-bc2d-545d3344987b
> Hyperlink: Add opacity to hyperlink default

- assets/css/v2/style.css
Closes https://github.com/nginxinc/docs-platform/issues/412
Before:
After:
> Set the grid row height to fit content instead of auto

- assets/css/v2/style.css
Closes https://github.com/nginxinc/docs-platform/issues/413
> Change cursor on hover for codeblock to text

- assets/css/v2/style.css
Removes height of `100vh` from sidebar as it is making the page longer than needed as seen in a page such as http://localhost:1313/nginx-gateway-fabric/reference/technical-specifications/
> Removed explicit height on sidebar

- assets/css/v2/style.css
- layouts/_default/baseof.html
- layouts/_default/docs.html
- layouts/partials/sidebar-v2.html
- layouts/search/single.html
Closes https://github.com/nginxinc/docs-platform/issues/398 and https://github.com/nginxinc/docs-platform/issues/403 and https://github.com/nginxinc/docs-platform/issues/410
Before (z-index issue):
After (z-index issue):
Before (sticky):
After (sticky):
> Coveo z-index + make sticky

- assets/css/v2/style.css
- assets/js/code-copy-v2.js
Closes https://github.com/nginxinc/docs-platform/issues/415
Default:
Hover:
Click:
> Add styling to codeblock copy button

- assets/css/v2/style.css
> fix: Add a little extra codeblock lineheight

- assets/css/v2/style.css
- assets/js/product-selector.js
- layouts/partials/sidebar-v2.html
Closes https://github.com/nginxinc/docs-platform/issues/416 and https://github.com/nginxinc/docs-platform/issues/411
> Product selector click is not working fully

- assets/css/v2/style.css
- assets/js/coveo.js
- layouts/_default/baseof.html
- layouts/_default/docs.html
- layouts/partials/header.html
- layouts/partials/sidebar-v2.html
- layouts/search/single.html
Closes https://github.com/nginxinc/docs-platform/issues/424
> Wider support for Coveo on Mobile + Edge cases

- assets/css/v2/style.css
Adds a little bit of vertical space when you click on a #link and a pure-CSS scroll animation, which is nice for when you click on heading links in the sidebar.
> Add smooth scrolling to #links

- assets/css/v2/style.css
- layouts/_default/baseof.html
- layouts/_default/list.html
ListPage: Add initial mf list page
> ListPage: Add initial mf list page

- assets/css/v2/style.css
Closes https://github.com/nginxinc/docs-platform/issues/404
> Extend all horizontal lines into the gutter

- Makefile
- layouts/_default/baseof.html
- tests/src/visual-regression.spec.js
Closes https://github.com/nginxinc/docs-platform/issues/436
> Refactor to use assertions instead for playwright

- layouts/_default/list.html
- layouts/partials/list-main.html
- layouts/partials/sidebar-v2.html
ListPage: Suppress list pages where products have content.
This needs to be released before https://github.com/nginx/documentation/pull/348 is merged.
Generic list in mf.
> ListPage: Suppress list pages where products have content

- exampleSite/content/test-product/call-out/all-callouts.md
- layouts/shortcodes/note.html
> Callout: Revert change to note callout

- assets/css/v2/style.css
- exampleSite/content/test-product/call-out/call-out-code-blocks.md
- exampleSite/content/test-product/call-out/call-out-code-lists.md
- exampleSite/content/test-product/call-out/call-out-side.md
- layouts/shortcodes/call-out.html
Use `minmax` to manage content and side-callout column
Remove device specific media queries
> Responsive: Fix callout handling and default side

- layouts/shortcodes/ghcode.html
Closes https://github.com/nginxinc/docs-platform/issues/425
Before:
After:
> Added styling to ghcode shortcode

- assets/css/v2/style.css
- layouts/_default/docs.html
- layouts/_default/list.html
Center justify text content. This matches responsive behaviour similar to stripe docs.
https://github.com/user-attachments/assets/b98905e7-01d7-4f8c-83fb-371453fcc151
> Grid: Center justify text content

- assets/css/v2/style.css
- exampleSite/content/test-product/code-blocks/code-blocks-highlighting.md
- layouts/shortcodes/highlight.html
Closes https://github.com/nginxinc/docs-platform/issues/463
Throws the following if `highlight` shortcode is used explicitly: 
> Throw error for highlight shortcode

- assets/css/v2/style.css
Closes https://github.com/nginxinc/docs-platform/issues/464
> Header for content grid expanding

- assets/css/v2/style.css
- layouts/_default/_markup/render-heading.html
Closes https://github.com/nginxinc/docs-platform/issues/433
Video to demonstrate hovering shows `#` within its bounds + there is a `#` on the current anchor link:
https://github.com/user-attachments/assets/9f155f24-da60-40f1-b86d-eb5d5609c849
> Add hashtag to headings

- assets/css/v2/style.css
- exampleSite/content/test-product/lucide/_index.md
- exampleSite/content/test-product/lucide/permitted.md
- layouts/_default/docs.html
- layouts/partials/lucide.html
- layouts/shortcodes/fe.html
- static/images/lucide-sprite.svg
Closes https://github.com/nginxinc/docs-platform/issues/462
> Icon support in MF + backwards compatability

- assets/css/v2/style.css
These updates are across the theme and `documentation` https://github.com/nginx/documentation/pull/451.
The current logos are _awkward_ so I ended up doing some transform to get things to line up nicely.
This is a **for now** homepage. We will come back and do something better when we have more input on content.
Screenshots here show different widths, and a `:hover` example. The pointer is set to cursor also, it's just awkward to screenshot.
**Preview link https://frontdoor-test-docs.nginx.com/previews/docs/8de07aa/**
> Homepage: Add basic homepage styling

- assets/css/v2/style.css
- exampleSite/content/test-product/everything.md
Closes https://github.com/nginxinc/docs-platform/issues/477
Before:
After:
> Add styling to details tag

- exampleSite/content/test-product/everything.md
- layouts/_default/_markup/render-heading.html
This wraps the header generation in a div, since hugo seemed to remove the extra attribute in the anchor, including removing `data-mf` for some reason.
Newframe working as expected
Oldframe without duplicate
> Headers: Fix duplicate oldframe header links

- assets/css/v2/style.css
Closes https://github.com/nginxinc/docs-platform/issues/465
Before:
After:
> Indent callout in list

- assets/css/v2/style.css
Note: leaving the transition commented out here because it causes a noticeable FOUC. Will need to find another solution, including for other links. It's a pretty subtle change.
Before:
After:
> Style: Add styling to linked inline code blocks

- assets/css/v2/style.css
- assets/js/coveo.js
- assets/js/sidebar-v2.js
- exampleSite/content/test-product/feather/_index.md
- exampleSite/content/test-product/sidebar/_index.md
- exampleSite/content/test-product/sidebar/nesting-1a/_index.md
- exampleSite/content/test-product/sidebar/nesting-1b/_index.md
- exampleSite/content/test-product/sidebar/nesting-1b/nesting-2/_index.md
- exampleSite/content/test-product/sidebar/nesting-1b/nesting-2/nesting-2-1.md
- exampleSite/content/test-product/sidebar/nesting-1b/nesting-2/nesting-2-2.md
- exampleSite/content/test-product/sidebar/nesting-1b/nesting-2/nesting-3/_index.md
- exampleSite/content/test-product/sidebar/nesting-1c/_index.md
- exampleSite/content/test-product/sidebar/nesting-1c/nesting-2/_index.md
- exampleSite/content/test-product/sidebar/nesting-1c/nesting-2/nesting-2-1.md
- exampleSite/content/test-product/sidebar/nesting-1c/nesting-2/nesting-2-2.md
- exampleSite/content/test-product/sidebar/nesting-1c/nesting-2/nesting-3/_index.md
- layouts/_default/docs.html
- layouts/_default/list.html
- layouts/partials/lucide.html
- layouts/partials/sidebar-list.html
- layouts/partials/sidebar-v2.html
- layouts/search/single.html
This is a from scratch sidebar implementation iterating on @danielledeleo branch and design feedback.
It should work like a sidebar, as expected 🤞 . 
Takes the `toc` frontmatter into account, to render or not render the table of contents.
Product selector and search are removed from the sidebar. The search now lives in the header, and the product selector will likely end up there as well, but it's not part of this PR.
The table of contents is within the sidebar still, and can be hidden/shown.
There are two a11y hidden links for skipping the sidebar entirely, or just skipping the table of contents you're on.
There's also a fix in here for icons, so that they resize properly via css.
I'd like to get this merged with it's current feature set, but there are some `TODOs` for future PRs:
- Add …
> Mainframe: Sidebar implemtation

- assets/css/v2/style.css
- assets/js/sidebar-v2.js
- exampleSite/content/test-product/sidebar/nesting-1b/_index.md
- layouts/partials/sidebar-list.html
Sidebar: Fix scroll height, remove chad comments
Removing the scrollIntoView for the sidebar. It's not working right, it scrolls the page content when it doesn't have some scrolling in the sidebar. Needs a different approach, so removing for now.
> Sidebar: Fix scroll height, remove chad comments

- assets/css/v2/style.css
Fixes whitespace in table of contents caused by `hX` elements we don't render (> 3).
This is a known issue in hugo - https://github.com/gohugoio/hugo/issues/7128
> Sidebar: Fix empty whitespace

- .pre-commit-config.yaml
Add [gitleaks](https://github.com/gitleaks/gitleaks) to our precommit checks.
This should only check for changes related to your commit, so it should run _very fast_ unless your commit is huge.
> Precommit: Add gitleaks scanning to precommit

- assets/css/v2/style.css
Due to https://github.com/nginxinc/nginx-hugo-theme/pull/245 being merged after https://github.com/nginxinc/nginx-hugo-theme/pull/237, some variable names were not updated to use oklch.
> Update colors to use oklch for new features

- exampleSite/content/test-product/tab-group/tab-group.md
- layouts/partials/callout.html
Remove whitespace when `icon` is not rendered in a callout.
_Only_ impacted callouts when nested in a tab group. 
See before and after for oldframe and new frame.
> Callout: Remove whitespace when icon not included

- assets/css/v2/style.css
- assets/js/sidebar-v2.js
- layouts/_default/docs.html
- layouts/_default/list.html
- layouts/partials/breadcrumb.html
Closes https://github.com/nginxinc/docs-platform/issues/466 and https://github.com/nginxinc/docs-platform/issues/490
> Sidebar Mobile Support

- assets/css/v2/style.css
- exampleSite/content/test-product/everything.md
Expandos were showing the pointer cursor on all elements in the expanded section, not just the expando link.
Also of note is the change to the first example that forces a `<p>` tag to be generated, improving whitespace.
This video shows the before and after:
https://github.com/user-attachments/assets/6a5c3041-ec4d-48a8-9295-b4c1bc258ba9
> Fix: Expandos no longer show pointer cursor on whole element

- exampleSite/content/test-product/prose/_index.md
- exampleSite/content/test-product/prose/nobreak.md
- layouts/shortcodes/nb.html
Shortcode: Add nobreak shortcode and usage example.
Example below uses `NGINX Plus (nobreak)` as an example.
> Shortcode: Add nobreak shortcode and usage exampl

- layouts/_default/docs.html
- layouts/_default/list.html
- layouts/partials/banner.html
- layouts/partials/list-main.html
- layouts/shortcodes/banner.html
Closes https://github.com/nginxinc/docs-platform/issues/489
> Added banner to list if front matter is present

- .gitignore
- assets/css/f5-hugo.css
Fix issue where oldframe was rendering redocly at a fixed small width.
> Redocly: Fix oldframe redocly width

- assets/css/v2/style.css
- layouts/partials/coveo-atomic.html
Moved `atomic-refine-toggle` (aka button to Sort and Filter) to a different place + add media query so it only shows up on mobile.
Reference: https://docs.coveo.com/en/atomic/latest/reference/components/atomic-refine-toggle/
> Refactor to add the coveo filter to mobile

- assets/css/f5-hugo.css
- assets/css/v2/style.css
- exampleSite/content/test-product/_index.md
- layouts/_default/list.html
- layouts/partials/custom-landing-page.html
- layouts/partials/list-main.html
- layouts/shortcodes/card-layout.html
- layouts/shortcodes/card-section.html
- layouts/shortcodes/card.html
- layouts/shortcodes/changelog-dates.html
Closes https://github.com/nginxinc/docs-platform/issues/519
> Added new shortcodes + partials to support custom landing page

- layouts/partials/banner.html
Adjust `banner` partial due to renamed param `banner` to be `nd-banner` found here - https://github.com/nginx/documentation/pull/732
> Refactor code due to param name change

- exampleSite/content/test-product/_index.md
- layouts/partials/list-main.html
- layouts/shortcodes/card.html
> Fix issues with double render

- assets/css/v2/style.css
- exampleSite/content/test-product/tables/examples/config-sharing.md
- layouts/404.html
- layouts/partials/table.html
- layouts/shortcodes/bootstrap-table.html
- layouts/shortcodes/table.html
This PR:
* Deprecates the `<bootstrap-table>` shortcode and implements the `<table>` shortcode as the _Mainframe_ table.
* Under the hood,`bootstrap-table` calls `table` with a default variant of "narrow" to maintain backwards compatibility
* Bootstrap _striped_ table handling not implemented.
* Documentation needed
* Implements a simple 404 page with new grid handling.
> Mainframe: Deprecate bootstrap-table + Basic 404 Page

- exampleSite/_banners/test-product-intro.md
- exampleSite/content/test-product/_index.md
- exampleSite/content/test-product/call-out/call-out-param-types.md
- exampleSite/content/test-product/call-out/call-out-side.md
- layouts/partials/callout.html
- layouts/shortcodes/banner.html
- layouts/shortcodes/before-you-begin.html
- layouts/shortcodes/call-out.html
- layouts/shortcodes/caution.html
- layouts/shortcodes/deprecated.html
- layouts/shortcodes/important.html
- layouts/shortcodes/note.html
- layouts/shortcodes/see-also.html
- layouts/shortcodes/tip.html
- layouts/shortcodes/warning.html
Closes https://github.com/nginxinc/docs-platform/issues/520
Before:
After:
> Fixed partially styled call-outs

- assets/css/v2/style.css
- exampleSite/content/_index.md
- exampleSite/content/test-product/_index.md
- exampleSite/content/test-product/call-out/all-callouts.md
- exampleSite/content/test-product/cards/_index.md
- exampleSite/content/test-product/cards/permitted.md
- exampleSite/layouts/index.html
- layouts/_default/list.html
- layouts/_default/single.html
- layouts/partials/callout.html
- layouts/partials/homepage.html
- layouts/redoc/single.html
- layouts/shortcodes/card-layout.html
- layouts/shortcodes/card-section.html
- layouts/shortcodes/card.html
- tests/src/cards.spec.js
Add .content class to handle overall content reflow 
Use scaling fonts
Refactor call outs to use grid utilities
~~TODO: Standard mobile sizes horz scroll on some pages~~
~~TODO: Homepage update to use grid utility~~
~~TODO: List card layout update to use grid utility~~
> Content: Replace with data attribute grid system

- assets/css/v2/style.css
- exampleSite/content/_index.md
- exampleSite/content/test-product/_index.md
- layouts/shortcodes/card-section.html
- layouts/shortcodes/card.html
- Refactored card CSS code to be more readable and organized.
- Fixed issues with URL path
- Fixed issue with images path
- Fixed layout issues with cards
> Fix Card + Refactor for readability

- assets/css/v2/style.css
Fixed issue with code blocks having too much vertical spacing due to default user agent styling. 
Before (single-line codeblock):
After:
Before (regular codeblock):
After:
Before (module single-line codeblock):
After:
> Update reset to include `pre` tag for code block

- assets/js/coveo.js
Noticed that on hard page refreshes, and slower connections that I would still see the extra vertical overflow caused by coveo. I assumed it was a race condition, and wrapping the removal of `atomic-relevance-inspector` in a timeout, would generally resolve it. I didn't want a timeout to be the "fix" here, so I added the Mutation Observer (https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) which appears to be the safest approach.
There's an overall 5 second timeout still, in case search never renders for whatever reason.
Coveo 😞 .
> Coveo: Fix vertical overflow race condition

- assets/css/v2/style.css
- exampleSite/content/test-product/call-out/all-callouts.md
- exampleSite/content/test-product/tab-group/tab-group.md
- layouts/_default/list.html
- layouts/partials/callout.html
- layouts/partials/table.html
This should match reasonably close to the original figma mockups, in terms of heading spacing, and outer table spacing. Other changes are best guess, but this also sets up variables to make tweaking a bit easier.
Spacing: Add margin variables throughout
Attempt to match figma spacing with headings
Add variables for ol and ul colours (Colour needs a review for sure!)
Fix icons in callouts
> Spacing 👾 

- assets/css/v2/style.css
- exampleSite/content/test-product/redoc/live-example.md
- exampleSite/static/api/one.json
- layouts/_default/baseof.html
- layouts/redoc/single.html
Close https://github.com/nginxinc/docs-platform/issues/576
> Fix width issues with Redocly + incorrect render of footer on redoc pages

- assets/css/v2/style.css
Closes https://github.com/nginxinc/docs-platform/issues/580
Before (Firefox):
After:
Verified it doesn't break as well in Chrome and Safari
> Fixed width for current page section button on Sidebar

- assets/css/v2/style.css
Switched to `rem` cause `ex` is not deterministic enough in this case.
> Fixed anchor scrolling by switching units

- assets/css/v2/style.css
- layouts/shortcodes/tabs.html
Closes: nginxinc/docs-platform/issues/422
Notable changes:
- `--magrin-tab-group` typo
- padding changes
- no more `border-bottom` underline
- simpler inline styles in `tabs.html`
Before:
After:
> TabGroup: Simpler underline style

- exampleSite/content/test-product/_index.md
- layouts/shortcodes/card.html
To better handle closing tags on `card` shortcode such as ```{{<card ... />}}```, the following need to be changed -
- Fix whitespace issues resulting in the following when rendered:
- Better handle case where there is no `.Inner` due to the closing tag. This results in more centered header as seen below:
Before: 
After:
> Handle case of no inner for cards

- assets/css/f5-hugo.css
Fixed issue of `auto` being set to 100% on Safari
Before:
After:
> Fix icon width on safari

- assets/css/v2/style.css
- exampleSite/content/test-product/tables/variations.md
- layouts/partials/table.html
- layouts/shortcodes/table.html
Tables: Add table themes and use data-grid.
Refactored the shortcode/partial to move all the error checking into the shortcode. 
This makes two themes available, usage covered in [variations.md](https://github.com/nginxinc/nginx-hugo-theme/compare/mainframe...mf-tables?expand=1#diff-bc5ab214e44aa3de995f9de0ede9c14664d6681a1fe3c899892f24f1ddc8c11d).
`bordered` works for larger datasets, but `borderless` is quite nice for smaller lists.
`bordered` theme
`borderless` theme
Includes fix for tables with inner `<hr>` - we'll figure out a table format that doesn't require hr's later.
> Tables: Add table themes and use data-grid

- assets/css/v2/style.css
- Add spacing 
Before:
After:
Before:
After:
> Add even spacing to cards

- assets/css/v2/style.css
- exampleSite/content/nginx/installing-nginx-open-source.md
- layouts/_default/single.html
Add optional "read time" using the `nd-reading-time` frontmatter.
Uses https://gohugo.io/methods/page/readingtime/ - Estimates can be configured based on reading WPM.
> Frontmatter: Add optional reading time

- layouts/_default/list.html
- layouts/partials/breadcrumb.html
- Removed FA icons from breadcrumb
- Fixed issue with cards being cut off due to `featured-section` param
> List page issues

- exampleSite/data/product-selector.yaml
- layouts/partials/sidebar-v2.html
Tweaks product selector schema to include an "extUrl" property. This property is then used in handling to assign `target="_blank"` when rendered.
Example:
```yaml
- productGroup: Test External Links
products:
- title: "NGINX.org"
url: https://nginx.org/index.html
extUrl: true
```
> ProductSelector: Open external links in a new tab

- assets/css/v2/style.css
Small collection of tweaks to adjust spacing and padding on the homepage.
* Also adjusts the sidebar to remove the unique styling for edge nodes as @danielledeleo had previously instructed 
> Homepage: Padding and spacing adjustments for Mainframe

- assets/css/v2/style.css
Fixes issue with scrolling still being active when Coveo filter modal is open on mobile devices.
> Lock scroll when coveo filter modal is open

- assets/css/v2/style.css
- layouts/_default/list.html
* Resolves awkward spacing for breadcrumbs on mobile landing pages
* Removes grid template row property which was causing the weird sizing. Spacing provided by the grid-template-row property was replaced with margin.
* Also adjusts the breadcrumb-layout element to data-grid="wide", fixing an issue where bottom borders extend half the screen on intermediate breakpoints. 
> Breadcrumbs: Adjust list page handling to resolve awkward mobile spacing

- exampleSite/content/_index.md
- exampleSite/content/nested-product/_index.md
- exampleSite/content/nested-product/get-help.md
- exampleSite/content/nested-product/module-changelog.md
- exampleSite/data/product-selector.yaml
- layouts/partials/sidebar-v2.html
* Resolves issues with subpaths resolution for products with a multi-part root path.
* New RE pattern was tested across current products without issue. 
Example Match:
> ProductSelector: Fix nested path resolution

- exampleSite/content/test-product/images/_index.md
- exampleSite/content/test-product/images/image-grid.md
- layouts/shortcodes/img.html
Img: Add data-grid support to img
Update example site with example
> Img: Add data-grid support to img

- exampleSite/content/_index.md
- exampleSite/content/nginx/installing-nginx-open-source.md
- layouts/_default/list.html
- layouts/partials/favicon.html
- layouts/partials/footer-v2.html
- layouts/partials/header.html
- layouts/partials/lucide.html
- layouts/partials/meta.html
- layouts/shortcodes/card.html
This forces all images to render using `absURL`, which should resolve any broken images in preview urls.
This will not fix images rendering by theme users that _don't_ use correct pathing. Possibly, we can add a build check for this later.
> Images: Fix images not rendering in preview

- exampleSite/content/test-product/mermaid/_index.md
- exampleSite/content/test-product/mermaid/mermaid-grid.md
- layouts/_default/_markup/render-codeblock-mermaid.html
Mermaid: Add grid support and exampleSite example.
See [test-product/mermaid/mermaid-grid](https://frontdoor-test-docs.nginx.com/previews/nginx-hugo-theme/412/test-product/mermaid/mermaid-grid/) in preview for usage.
> Mermaid: Add grid support and exampleSite example

- assets/css/v2/style.css
Before:
After:
Edge case (mulit-line text):
> Fix heading anchor link icon alignment
